[default.extend-identifiers]
SPlisHSPlasH = "SPlisHSPlasH"

[default.extend-words]
ba = "ba"
Comput = "Comput"
Shepard = "Shepard"
shepard = "shepard"
Strack = "Strack"
Lok = "Lok"
PN = "PN"
Typ = "Typ"
Yiu = "Yiu"
