include("solid/total_lagrangian_sph/total_lagrangian_sph.jl")
include("boundary/dummy_particles/dummy_particles.jl")
include("boundary/monaghan_kajtar/monaghan_kajtar.jl")
include("boundary/open_boundary/characteristic_variables.jl")
include("fluid/fluid.jl")
