steps:
  - label: "CUDA.jl"
    plugins:
      - JuliaCI/julia#v1:
          version: "1"
    agents:
      queue: "juliagpu"
      cuda: "*"
    command: |
      julia --color=yes --project=test -e 'using Pkg; Pkg.add("CUDA"); Pkg.develop(path="."); Pkg.instantiate()'
      julia --color=yes --project=test -e 'include("test/runtests.jl")'
    env:
      TRIXIPARTICLES_TEST: cuda
    timeout_in_minutes: 60
