const PANEL_DIRECTORY = "panels"

function panel_output(figure, panel)
    joinpath(PANEL_DIRECTORY,
             "figure_$(lpad(figure, 2, '0'))_$(panel).png")
end

const BLUE_SOLID = (0.02f0, 0.18f0, 0.55f0)
const PALE_SOLID = (0.72f0, 0.75f0, 0.78f0)
const BOX_SOLID = (0.74f0, 0.73f0, 0.64f0)

const WATER_CROWN_PROPS = ((; kind=:box, origin=(-0.005, -0.008, -0.005),
                            widths=(0.16, 0.01, 0.05), color=BLUE_SOLID),
                           (; kind=:box, origin=(-0.005, 0.148, -0.005),
                            widths=(0.16, 0.01, 0.05), color=BLUE_SOLID),
                           (; kind=:box, origin=(-0.008, 0.0, -0.005),
                            widths=(0.01, 0.15, 0.05), color=BLUE_SOLID),
                           (; kind=:box, origin=(0.148, 0.0, -0.005),
                            widths=(0.01, 0.15, 0.05), color=BLUE_SOLID))

const PLATE_PROPS = ((; kind=:box, origin=(-0.2, -0.2, -0.025),
                      widths=(0.4, 0.4, 0.025), color=PALE_SOLID),
                     (; kind=:box, origin=(-0.025, -0.025, -0.2),
                      widths=(0.05, 0.05, 0.175), color=PALE_SOLID))

const WETTING_PROPS = ((; kind=:box, origin=(-0.03, -0.03, -0.002),
                        widths=(0.06, 0.06, 0.002), color=PALE_SOLID),)

const SPLITTING_PROPS = ((; kind=:box, origin=(0.0, 0.0, -0.02),
                          widths=(0.24, 0.18, 0.02), color=BOX_SOLID),
                         (; kind=:box, origin=(-0.02, 0.0, -0.02),
                          widths=(0.02, 0.18, 0.16), color=BOX_SOLID),
                         (; kind=:box, origin=(0.24, 0.0, -0.02),
                          widths=(0.02, 0.18, 0.16), color=BOX_SOLID),
                         (; kind=:box, origin=(0.0, 0.18, -0.02),
                          widths=(0.24, 0.02, 0.16), color=BOX_SOLID))

const CASES = ((name="water_crown",
                title="Figures 1 and 5: water crown",
                example="akinci_water_crown_3d.jl",
                kwargs=(; particle_spacing=0.0015, tspan=(0.0, 0.12),
                        solution_saveat=(0.0, 0.025, 0.045, 0.055, 0.075, 0.095, 0.12),
                        saving_callback=nothing),
                system_indices=(1,), focus_indices=(1,), fluid_iso_fraction=0.12f0,
                view_center=(0.075, 0.075, 0.04), view_extent=0.18f0,
                camera=(0.15, -2.0, 0.32), camera_scale=1.85f0, fov=28.0f0,
                props=WATER_CROWN_PROPS, show_ground=false,
                panels=((; time=0.0, output=panel_output(1, 1)),
                        (; time=0.025, output=panel_output(1, 2)),
                        (; time=0.055, output=panel_output(1, 3)),
                        (; time=0.12, output=panel_output(5, 2)))),
               (name="cube_to_sphere",
                title="Figure 2c: Akinci surface-tension model",
                example="akinci_cube_to_sphere_3d.jl",
                kwargs=(; release_time=0.05, tspan=(0.0, 0.1),
                        solution_saveat=(0.0, 0.03, 0.05, 0.065, 0.075, 0.08, 0.085,
                                         0.09, 0.095, 0.1),
                        saving_callback=nothing),
                paper=(; fluid_volume=1.0e-6, particle_count=7_000,
                       source=:companion_video),
                system_indices=(1,), focus_indices=(1,), render_style=:particles,
                particle_color=:pressure,
                particle_scale=0.82f0, view_center=(0.0, 0.0, 0.006), view_extent=0.03f0,
                camera=(1.1, -2.0, 0.72), camera_scale=2.0f0, fov=30.0f0,
                props=((; kind=:box, origin=(-0.015, -0.015, -0.002),
                        widths=(0.03, 0.03, 0.002), color=PALE_SOLID),),
                show_ground=false,
                panels=((; time=0.05, output=panel_output(2, 1)),
                        (; time=0.1, output=panel_output(2, 2)))),
               (name="droplet_on_plate",
                title="Figure 6: droplet impact on a plate",
                example="akinci_droplet_on_plate_3d.jl",
                kwargs=(; particle_spacing=0.02, drop_radius=0.12,
                        drop_center=(0.0, 0.0, 0.28), plate_size=(0.4, 0.4),
                        tspan=(0.0, 0.25), solution_saveat=(0.0, 0.15, 0.2, 0.25),
                        saving_callback=nothing),
                system_indices=(1,), focus_indices=(1,), fluid_iso_fraction=0.15f0,
                view_center=(0.0, 0.0, 0.08), view_extent=0.56f0,
                camera=(1.0, -2.0, 0.85), camera_scale=1.9f0, fov=30.0f0,
                props=PLATE_PROPS, show_ground=false,
                panels=((; time=0.0, output=panel_output(6, 1), camera=(0.2, -2.0, 0.35)),
                        (; time=0.15, output=panel_output(6, 2), camera=(0.4, -2.0, 0.55)),
                        (; time=0.2, output=panel_output(6, 3)),
                        (; time=0.25, output=panel_output(6, 4)))),
               (name="stream_over_sphere_1",
                title="Figure 7: stream flowing over a sphere",
                example="akinci_stream_over_sphere_3d.jl",
                kwargs=(; particle_spacing=0.015, tspan=(0.0, 0.08),
                        solution_saveat=(0.08,), saving_callback=nothing),
                system_indices=(1, 3), focus_indices=(1, 3),
                view_center=(0.0, 0.0, -0.12), view_extent=0.32f0,
                camera=(0.4, -2.0, 0.25), camera_scale=2.0f0, fov=28.0f0,
                system_colors=(3 => PALE_SOLID,), show_ground=false,
                panels=((; time=0.08, output=panel_output(7, 1)),)),
               (name="stream_over_sphere_2",
                title="Figure 7: stream flowing over a sphere",
                example="akinci_stream_over_sphere_3d.jl",
                kwargs=(; particle_spacing=0.015, tspan=(0.0, 0.18),
                        solution_saveat=(0.18,), saving_callback=nothing),
                system_indices=(1, 3), focus_indices=(1, 3),
                view_center=(0.0, 0.0, -0.12), view_extent=0.32f0,
                camera=(0.4, -2.0, 0.25), camera_scale=2.0f0, fov=28.0f0,
                system_colors=(3 => PALE_SOLID,), show_ground=false,
                panels=((; time=0.18, output=panel_output(7, 2)),)),
               (name="stream_over_sphere_3",
                title="Figure 7: stream flowing over a sphere",
                example="akinci_stream_over_sphere_3d.jl",
                kwargs=(; particle_spacing=0.015, tspan=(0.0, 0.3),
                        solution_saveat=(0.3,), saving_callback=nothing),
                system_indices=(1, 3), focus_indices=(1, 3),
                view_center=(0.0, 0.0, -0.12), view_extent=0.32f0,
                camera=(0.4, -2.0, 0.25), camera_scale=2.0f0, fov=28.0f0,
                system_colors=(3 => PALE_SOLID,), show_ground=false,
                panels=((; time=0.3, output=panel_output(7, 3)),)),
               (name="stream_over_sphere_4",
                title="Figure 7: stream flowing over a sphere",
                example="akinci_stream_over_sphere_3d.jl",
                kwargs=(; particle_spacing=0.015, tspan=(0.0, 0.45),
                        solution_saveat=(0.45,), saving_callback=nothing),
                system_indices=(1, 3), focus_indices=(1, 3),
                view_center=(0.0, 0.0, -0.12), view_extent=0.32f0,
                camera=(0.4, -2.0, 0.25), camera_scale=2.0f0, fov=28.0f0,
                system_colors=(3 => PALE_SOLID,), show_ground=false,
                panels=((; time=0.45, output=panel_output(7, 4)),)),
               (name="wetting_no",
                title="Figure 8: no wetting",
                example="akinci_wetting_3d.jl",
                kwargs=(; wetting_case="no_wetting", plate_size=(0.06, 0.06),
                        tspan=(0.0, 0.2), solution_saveat=(0.0, 0.05, 0.1, 0.15, 0.2),
                        saving_callback=nothing),
                paper=(; fluid_volume=1.0e-6, particle_count=750,
                       surface_tension_coefficient=1.0, adhesion_coefficient=0.0,
                       source=:companion_video),
                system_indices=(1,), focus_indices=(1,), fluid_iso_fraction=0.15f0,
                view_center=(0.0, 0.0, 0.004), view_extent=0.07f0,
                camera=(0.8, -2.0, 0.38), camera_scale=1.9f0, fov=29.0f0,
                props=WETTING_PROPS, show_ground=false,
                panels=((; time=0.2, output=panel_output(8, 1)),)),
               (name="wetting_weak",
                title="Figure 8 video: weak wetting",
                example="akinci_wetting_3d.jl",
                kwargs=(; wetting_case="weak_wetting", plate_size=(0.06, 0.06),
                        tspan=(0.0, 0.2), solution_saveat=(0.0, 0.05, 0.1, 0.15, 0.2),
                        saving_callback=nothing),
                paper=(; fluid_volume=1.0e-6, particle_count=750,
                       surface_tension_coefficient=1.0, adhesion_coefficient=0.05,
                       source=:companion_video),
                system_indices=(1,), focus_indices=(1,), fluid_iso_fraction=0.15f0,
                view_center=(0.0, 0.0, 0.004), view_extent=0.07f0,
                camera=(0.8, -2.0, 0.38), camera_scale=1.9f0, fov=29.0f0,
                props=WETTING_PROPS, show_ground=false, panels=()),
               (name="wetting_moderate",
                title="Figure 8: moderate wetting",
                example="akinci_wetting_3d.jl",
                kwargs=(; wetting_case="moderate_wetting", plate_size=(0.06, 0.06),
                        tspan=(0.0, 0.2), solution_saveat=(0.0, 0.05, 0.1, 0.15, 0.2),
                        saving_callback=nothing),
                paper=(; fluid_volume=1.0e-6, particle_count=750,
                       surface_tension_coefficient=1.0, adhesion_coefficient=0.1,
                       source=:companion_video),
                system_indices=(1,), focus_indices=(1,), fluid_iso_fraction=0.15f0,
                view_center=(0.0, 0.0, 0.004), view_extent=0.07f0,
                camera=(0.8, -2.0, 0.38), camera_scale=1.9f0, fov=29.0f0,
                props=WETTING_PROPS, show_ground=false,
                panels=((; time=0.2, output=panel_output(8, 2)),)),
               (name="wetting_intermediate",
                title="Figure 8: intermediate wetting",
                example="akinci_wetting_3d.jl",
                kwargs=(; wetting_case="intermediate_wetting", plate_size=(0.06, 0.06),
                        tspan=(0.0, 0.2), solution_saveat=(0.0, 0.05, 0.1, 0.15, 0.2),
                        saving_callback=nothing),
                paper=(; fluid_volume=1.0e-6, particle_count=750,
                       surface_tension_coefficient=1.0, adhesion_coefficient=0.25,
                       source=:companion_video),
                system_indices=(1,), focus_indices=(1,), fluid_iso_fraction=0.15f0,
                view_center=(0.0, 0.0, 0.004), view_extent=0.07f0,
                camera=(0.8, -2.0, 0.38), camera_scale=1.9f0, fov=29.0f0,
                props=WETTING_PROPS, show_ground=false,
                panels=((; time=0.2, output=panel_output(8, 3)),)),
               (name="wetting_strong",
                title="Figure 8 video: strong wetting",
                example="akinci_wetting_3d.jl",
                kwargs=(; wetting_case="strong_wetting", plate_size=(0.06, 0.06),
                        tspan=(0.0, 0.2), solution_saveat=(0.0, 0.05, 0.1, 0.15, 0.2),
                        saving_callback=nothing),
                paper=(; fluid_volume=1.0e-6, particle_count=750,
                       surface_tension_coefficient=0.1, adhesion_coefficient=0.01,
                       source=:companion_video),
                system_indices=(1,), focus_indices=(1,), fluid_iso_fraction=0.15f0,
                view_center=(0.0, 0.0, 0.004), view_extent=0.07f0,
                camera=(0.8, -2.0, 0.38), camera_scale=1.9f0, fov=29.0f0,
                props=WETTING_PROPS, show_ground=false, panels=()),
               (name="wetting_near_perfect",
                title="Figure 8 video: near-perfect wetting",
                example="akinci_wetting_3d.jl",
                kwargs=(; wetting_case="near_perfect_wetting", plate_size=(0.06, 0.06),
                        tspan=(0.0, 0.2), solution_saveat=(0.0, 0.05, 0.1, 0.15, 0.2),
                        saving_callback=nothing),
                paper=(; fluid_volume=1.0e-6, particle_count=750,
                       surface_tension_coefficient=0.01, adhesion_coefficient=0.001,
                       source=:companion_video),
                system_indices=(1,), focus_indices=(1,), fluid_iso_fraction=0.15f0,
                view_center=(0.0, 0.0, 0.004), view_extent=0.07f0,
                camera=(0.8, -2.0, 0.38), camera_scale=1.9f0, fov=29.0f0,
                props=WETTING_PROPS, show_ground=false, panels=()),
               (name="wetting_perfect",
                title="Figure 8: perfect wetting",
                example="akinci_wetting_3d.jl",
                kwargs=(; wetting_case="perfect_wetting", plate_size=(0.06, 0.06),
                        tspan=(0.0, 0.2), solution_saveat=(0.0, 0.05, 0.1, 0.15, 0.2),
                        saving_callback=nothing),
                paper=(; fluid_volume=1.0e-6, particle_count=750,
                       surface_tension_coefficient=0.001, adhesion_coefficient=0.0,
                       source=:companion_video),
                system_indices=(1,), focus_indices=(1,), fluid_iso_fraction=0.15f0,
                view_center=(0.0, 0.0, 0.004), view_extent=0.07f0,
                camera=(0.8, -2.0, 0.38), camera_scale=1.9f0, fov=29.0f0,
                props=WETTING_PROPS, show_ground=false,
                panels=((; time=0.2, output=panel_output(8, 4)),)),
               (name="droplet_splitting",
                title="Figure 9: droplet splitting in an adhesive box",
                example="akinci_droplet_splitting_3d.jl",
                kwargs=(; particle_spacing=0.01, tspan=(0.0, 0.35),
                        solution_saveat=(0.0, 0.12, 0.22, 0.35), saving_callback=nothing),
                system_indices=(1, 3), focus_indices=(1, 3), fluid_iso_fraction=0.15f0,
                view_center=(0.12, 0.09, 0.07), view_extent=0.29f0,
                camera=(0.7, -2.0, 0.7), camera_scale=2.1f0, fov=30.0f0,
                system_colors=(3 => (1.0f0, 0.65f0, 0.0f0),),
                props=SPLITTING_PROPS, show_ground=false,
                panels=((; time=0.0, output=panel_output(9, 1)),
                        (; time=0.12, output=panel_output(9, 2)),
                        (; time=0.22, output=panel_output(9, 3)),
                        (; time=0.35, output=panel_output(9, 4)))),
               (name="rolling_droplet",
                title="Figure 10: rolling droplet",
                example="akinci_rolling_droplet_3d.jl",
                kwargs=(; particle_spacing=0.01, tspan=(0.0, 0.4),
                        solution_saveat=(0.0, 0.12, 0.26, 0.4), saving_callback=nothing),
                system_indices=(1, 2, 3, 4), focus_indices=(1, 3, 4),
                fluid_iso_fraction=0.2f0,
                view_center=(0.0, 0.0, 0.09), view_extent=0.58f0,
                camera=(0.0, -2.0, 0.35), camera_scale=1.9f0, fov=29.0f0,
                system_colors=(2 => BLUE_SOLID,
                               3 => (0.15f0, 0.8f0, 0.25f0),
                               4 => (0.95f0, 0.15f0, 0.65f0)),
                show_ground=false,
                panels=((; time=0.0, output=panel_output(10, 1)),
                        (; time=0.12, output=panel_output(10, 2)),
                        (; time=0.26, output=panel_output(10, 3)),
                        (; time=0.4, output=panel_output(10, 4)))))

# CSS variants are admitted one case at a time after their raw-particle metric exists. The
# coefficient is a Track B calibration candidate, not a physical material property.
const CSS_CASES = ((name="cube_to_sphere_css",
                    base_name="cube_to_sphere",
                    title="Figure 2c: CSS surface-tension model",
                    surface_tension_coefficient=0.012,
                    surface_tension_mode=:css,
                    smoothing_kernel_mode=:wendland_c2,
                    smoothing_length_ratio=1.4,
                    normal_smoothing=false,
                    ccsf_contact_angle=nothing,
                    artificial_viscosity_alpha=0.05,
                    viscosity_mode=:artificial_monaghan,
                    density_diffusion_mode=:antuono,
                    density_diffusion_delta=0.1,
                    initial_particle_distribution=:lattice,
                    packing_relative_jitter=0.1,
                    packing_seed=20260805,
                    packing_maxiters=1000,
                    pressure_stabilization=:none,
                    tic_strength=1.0,
                    shifting_mode=:consistent_sun2019,
                    shifting_v_max_factor=0.0f0,
                    shifting_sound_speed_factor=0.1f0,
                    particle_spacing=0.01 / 19,
                    contact_angle=nothing,
                    calibration_status=:alignment_corrected_candidate),)

const PLATES = ((output="figure_01_water_crown.png",
                 title="Figure 1 | Water-crown sequence",
                 caption="The reported pool and drop dimensions produce the initial impact and crown at reduced resolution.",
                 layout=(1, 3),
                 cells=((; file=panel_output(1, 1), label="before impact"),
                        (; file=panel_output(1, 2), label="first impact"),
                        (; file=panel_output(1, 3), label="crown and spray"))),
                (output="figure_02_surface_tension.png",
                 title="Figure 2c | Implemented surface-tension model",
                 caption="Only the Akinci model represented by row (c) of the paper is available in this repository.",
                 layout=(1, 2),
                 cells=((; file=panel_output(2, 1), label="relaxed droplet"),
                        (; file=panel_output(2, 2), label="post-impact"))),
                (output="figure_05_model_comparison.png",
                 title="Figure 5 | Water-crown model comparison",
                 caption="The unavailable Becker-Teschner comparison is left explicit instead of being approximated by another model.",
                 layout=(1, 2),
                 cells=((; placeholder="Becker and Teschner (2007)\nnot implemented",
                         label="comparison model"),
                        (; file=panel_output(5, 2), label="Akinci model"))),
                (output="figure_06_droplet_on_plate.png",
                 title="Figure 6 | Droplet impact on a finite plate",
                 caption="The scaled sequence follows approach, impact, sheet formation, and dripping.",
                 layout=(1, 4),
                 cells=((; file=panel_output(6, 1), label="approach"),
                        (; file=panel_output(6, 2), label="impact"),
                        (; file=panel_output(6, 3), label="sheet"),
                        (; file=panel_output(6, 4), label="dripping"))),
                (output="figure_07_stream_over_sphere.png",
                 title="Figure 7 | Stream flowing over a sphere",
                 caption="Each panel is an independent final-time run so the mutable open-boundary mask remains valid.",
                 layout=(1, 4),
                 cells=((; file=panel_output(7, 1), label="contact"),
                        (; file=panel_output(7, 2), label="coating"),
                        (; file=panel_output(7, 3), label="through-flow"),
                        (; file=panel_output(7, 4), label="late flow"))),
                (output="figure_08_wetting.png",
                 title="Figure 8 | Wetting regimes",
                 caption="The reported coefficient pairs are retained, but raw WCSPH diagnostics do not reproduce the reference regimes.",
                 layout=(1, 4),
                 cells=((; file=panel_output(8, 1), label="gamma=1, beta=0"),
                        (; file=panel_output(8, 2), label="gamma=1, beta=0.1"),
                        (; file=panel_output(8, 3), label="gamma=1, beta=0.25"),
                        (; file=panel_output(8, 4), label="gamma=0.001, beta=0"))),
                (output="figure_09_droplet_splitting.png",
                 title="Figure 9 | Splitting in an adhesive box",
                 caption="The box is adhesive while the descending yellow blade has zero adhesion.",
                 layout=(1, 4),
                 cells=((; file=panel_output(9, 1), label="initial state"),
                        (; file=panel_output(9, 2), label="first contact"),
                        (; file=panel_output(9, 3), label="separation"),
                        (; file=panel_output(9, 4), label="split droplet"))),
                (output="figure_10_rolling_droplet.png",
                 title="Figure 10 | Rolling droplet and rigid figures",
                 caption="Green and pink identify the adhesive and non-adhesive rigid figures, respectively.",
                 layout=(1, 4),
                 cells=((; file=panel_output(10, 1), label="release"),
                        (; file=panel_output(10, 2), label="rolling"),
                        (; file=panel_output(10, 3), label="interaction"),
                        (; file=panel_output(10, 4), label="late state"))))

function akinci_case_config(name)
    index = findfirst(config -> config.name == name, CASES)
    isnothing(index) && return nothing
    return CASES[index]
end

function case_config(name)
    base = akinci_case_config(name)
    !isnothing(base) && return base

    index = findfirst(config -> config.name == name, CSS_CASES)
    if !isnothing(index)
        css = CSS_CASES[index]
        base = akinci_case_config(css.base_name)
        isnothing(base) &&
            error("CSS case '$name' has unknown base case '$(css.base_name)'")
        return merge(base, (; name=css.name, title=css.title, css))
    end

    available = (getproperty.(CASES, :name)..., getproperty.(CSS_CASES, :name)...)
    error("unknown comparison case '$name'. Available cases: " * join(available, ", "))
end
